#ifndef VISUALIZATIONCORE_GLOBAL_H
#define VISUALIZATIONCORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(VISUALIZATIONCORE_LIBRARY)
#  define VISUALIZATIONCORESHARED_EXPORT Q_DECL_EXPORT
#else
#  define VISUALIZATIONCORESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // VISUALIZATIONCORE_GLOBAL_H
